---
title: "PRC Airport Operations Centres (APOC) Performance Study"
type: "Performance Study"
date: '2025-04-04'
excerpt: "Performance Study"
bibliography: [../../../static/bib/aviation.bib]
link-citations: true
dwnld_i: <i class="fa pru fa-download"></i>
tags: Performance Study, Airport Operations
---
```{r echo = FALSE, message = FALSE, warning = FALSE}
# run setup script
source(here::here("_common.R"))
```
 
<br>
<div class="container">
<div class="row align-items-start">


The Transformation Support Strategy (TSS) of the independent Performance Review Commission (PRC) helps to analyse how emerging technologies enhance the European ATM system performance. As part of this, the Airport Operation Centre (APOC) concept was selected as a flagship project.

APOCs serve as collaborative platforms for key airport stakeholders, enhancing decision-making, coordination, and operational efficiency through shared knowledge and a unified, coordinated approach.

Beyond digital transformation, APOC implementation requires a cultural shift, fostering collaboration among airlines, airport operators, ground handlers, ANSPs, and the Network Manager.

The study provides: 

- A high-level overview of the APOC concept.
- A catalogue of possible performance indicators for APOC monitoring activities.
- A summary of reported benefits and key recommendations.
- An inventory of APOC implementations across Europe.

By detailing these elements, the document aims to offer a comprehensive understanding of the APOC concept and current implementations together with the potential performance improvements from the ATM perspective.

Download the full report below to find out more.



<br><br><a href="/library/eurocontrol-prc-apoc-study.pdf" data-toggle="tooltip" title="Download pdf version" target="_blank" class="btn btn-info" role="button"> PRC Airport Operations Centres (APOC) Performance Study <br> {{% dwnld_i %}} Download </a>

#### Notice
*The PRC has made every effort to ensure that the information and analysis contained in this document are as accurate and 
complete as possible. Despite these precautions, should you find any errors or inconsistencies we would be grateful if you 
could please bring them to the [Aviation Intelligence Unit's attention](mailto:PRU-Support@eurocontrol.int).*


</div>
</div>

[apoc]: /library/eurocontrol-prc-apoc-study.pdf "PRC Airport Operations Centres (APOC) Performance Study"