#------- LOCAL DEVELOPMENT/TESTING -------
# remember ending '/'
# baseurl = "/"
# see .Rprofile for publishDir, i.e. the place
# where generated HTML is put (the "public" dir in hugo parlance)
#-----------------------------------------


#--------------- PRODUCTION ---------------
# remember ending '/'
baseurl = "https://www.ansperformance.eu/"
# publishDir = "public/"
#-----------------------------------------



languageCode = "en-us"
title = "Aviation Intelligence Portal"
theme = "pru-theme"

# Deni's one
googleAnalytics = "G-RJ3R0C35X7"
summaryLength = 10

ignoreFiles = [
  "\\.knit\\.md$",
  "\\.utf8\\.md$",
  "\\.Rmd$",
  "\\.Rmarkdown$",
  "_cache$",
  "src$"
]

# keep embedded HTML, see data.md
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true



# Uncomment below to enable syntax highlighting
# pygmentsCodefences = true
# pygmentsCodefencesGuessSyntax = true
# See https://xyproto.github.io/splash/docs/all.html for more styles
# pygmentsStyle = "pygments"

[taxonomies]
  tag = "tags"

[permalinks]
    post = "/:year/:month/:day/:slug/"

# See https://feathericons.com/
# The value of pre is the icon name
[menu]

 [[menu.main]]
    name = "Home"
    identifier= "aiu"
    url = "/#/"
    weight = 5

  [[menu.main]]
    name = "Performance areas"
    identifier = "dashboard"
    pre = ""
    url = "/dashboard/"
    weight = 15
  #----------------------
  [[menu.main]]
    pre = "<i class='fas fa-th'></i>"
    name = "&nbsp;Balanced scorecard"
    url = "https://www.eurocontrol.int/Economics/BalancedScorecard.html"
    identifier = "key-balanced-scorecard"
    parent = "dashboard"
    weight = 15
  [[menu.main]]
    pre = "<i class='fas fa-plane-departure'></i>"
    name = "&nbsp;Traffic"
    url = "/traffic/"
    identifier = "key-traffic"
    parent = "dashboard"
    weight = 16
    [[menu.main]]
  #   pre = "&nbsp;&nbsp;&nbsp;<i class='far fa-star fa-spin fa-fw'></i>"
      name = "&nbsp;&nbsp;&nbsp;&nbsp;<span style='font-weight: normal'>Daily traffic dashboard</span></i>"
      url = "https://www.eurocontrol.int/Economics/DailyTrafficVariation-States.html"
      identifier = "key-traffic-daily-traffic"
      parent = "dashboard"
      weight = 17
    [[menu.main]]
      pre = "&nbsp;&nbsp;&nbsp;"
      name = " <span style='font-weight: normal'>Service units</span>"
      url = "https://www.eurocontrol.int/ServiceUnits/Dashboard/EnRouteMainDashboard.html"
      identifier = "key-service-units"
      parent = "dashboard"
      weight = 19
    [[menu.main]]
      pre = "&nbsp;&nbsp;&nbsp;"
      name = " <span style='font-weight: normal'>Traffic forecast</span>"
      url = "/traffic/statfor/"
      identifier = "key-traffic-forecast"
      parent = "dashboard"
      weight = 19
  #----------------------
  [[menu.main]]
    pre = "<i class='fas fa-calendar'></i>"
    name = "&nbsp;Punctuality"
    url = "/traffic/punctuality/"
    identifier = "key-punctuality"
    parent = "dashboard"
    weight = 20
    [[menu.main]]
      pre = "&nbsp;&nbsp;&nbsp;"
      name = " <span style='font-weight: normal'>Network punctuality</span>"
      url = "/traffic/punctuality/#eurocontrol-area-network-view-1"
      identifier = "key-punctuality-network"
      parent = "dashboard"
      weight = 21
    [[menu.main]]
      pre = "&nbsp;&nbsp;&nbsp;"
      name = " <span style='font-weight: normal'>State & airport punctuality</span>"
      url = "/traffic/punctuality/#state-view-1"
      identifier = "key-punctuality-state-airport"
      parent = "dashboard"
      weight = 22
  #----------------------
  [[menu.main]]
    pre = "<i class='fas fa-clock'></i>"
    name = "&nbsp;En-route & airport delays"
    url = "/capacity/"
    identifier = "key-capacity"
    parent = "dashboard"
    weight = 23
    [[menu.main]]
      pre = "&nbsp;&nbsp;&nbsp;"
      name = " <span style='font-weight: normal'>En-route ATFM delays</span>"
      url = "/capacity/atfm_ert/"
      identifier = "key-enroute-atfm"
      parent = "dashboard"
      weight = 24
    [[menu.main]]
      pre = "&nbsp;&nbsp;&nbsp;"
      name = " <span style='font-weight: normal'>Airport ATFM delays</span>"
      url = "/capacity/atfm_apt/"
      identifier = "key-atfm-apt"
      parent = "dashboard"
      weight = 25
    [[menu.main]]
      pre = "&nbsp;&nbsp;&nbsp;"
      name = " <span style='font-weight: normal'>All-causes delays</span>"
      url = "/capacity/tot_dly/"
      identifier = "key-tot-dly"
      parent = "dashboard"
      weight = 26
  #----------------------
  [[menu.main]]
    pre = "<i class='fas fa-leaf'></i>"
    name = "&nbsp;Efficiency & environment"
    url = "/efficiency/"
    identifier = "key-environment"
    parent = "dashboard"
    weight = 27
    [[menu.main]]
      pre = "&nbsp;&nbsp;&nbsp;"
      name = " <span style='font-weight: normal'>CO<sub>2</sub> emissions</span>"
      url = "/efficiency/emissions/"
      identifier = "key-environment-emissions"
      parent = "dashboard"
      weight = 28
     [[menu.main]]
      pre = "&nbsp;&nbsp;&nbsp;"
      name = " <span style='font-weight: normal'>Horizontal flight efficiency</span>"
      url = "/efficiency/hfe/"
      identifier = "key-environment-hfe"
      parent = "dashboard"
      weight = 29
    [[menu.main]]
      pre = "&nbsp;&nbsp;&nbsp;"
      name = " <span style='font-weight: normal'>Vertical flight efficiency</span>"
      url = "/efficiency/vfe/"
      identifier = "key-environment-vfe"
      parent = "dashboard"
      weight = 30
    [[menu.main]]
      pre = "&nbsp;&nbsp;&nbsp;"
      name = " <span style='font-weight: normal'>Terminal holdings</span>"
      url = "/efficiency/asma/"
      identifier = "key-environment-holding"
      parent = "dashboard"
      weight = 31
    [[menu.main]]
      pre = "&nbsp;&nbsp;&nbsp;"
      name = " <span style='font-weight: normal'>Taxi-out</span>"
      url = "/efficiency/taxiout/"
      identifier = "key-environment-taxiout"
      parent = "dashboard"
      weight = 32
    [[menu.main]]
      pre = "&nbsp;&nbsp;&nbsp;"
      name = " <span style='font-weight: normal'>Taxi-in</span>"
      url = "/efficiency/taxiin/"
      identifier = "key-environment-taxiin"
      parent = "dashboard"
      weight = 33
  #----------------------
  [[menu.main]]
    pre = "<i class='fas fa-euro-sign'></i>"
    name = "&nbsp;Economics"
    url = "/economics/"
    identifier = "key-economics"
    parent = "dashboard"
    weight = 34
    [[menu.main]]
      pre = "&nbsp;&nbsp;&nbsp;"
      name = " <span style='font-weight: normal'>ATM cost-effectiveness (ACE)</span>"
      url = "/economics/ace-overview/"
      identifier = "key-economics-ace"
      parent = "dashboard"
      weight = 35
    [[menu.main]]
      pre = "&nbsp;&nbsp;&nbsp;"
      name = " <span style='font-weight: normal'>Unit rates and costs</span>"
      url = "https://www.eurocontrol.int/ServiceUnits/Dashboard/EnRouteUnitRates.html"
      identifier = "key-economics-unit-rates"
      parent = "dashboard"
      weight = 36
    [[menu.main]]
      pre = "&nbsp;&nbsp;&nbsp;"
      name = " <span style='font-weight: normal'>Service units</span>"
      url = "https://www.eurocontrol.int/ServiceUnits/Dashboard/EnRouteMainDashboard.html"
      identifier = "key-economics-service-units"
      parent = "dashboard"
      weight = 37
    [[menu.main]]
      pre = "&nbsp;&nbsp;&nbsp;"
      name = " <span style='font-weight: normal'>ANSPs financial dashboard</span>"
      url = "/economics/finance/"
      identifier = "key-economics-financial"
      parent = "dashboard"
      weight = 38
    [[menu.main]]
      pre = "&nbsp;&nbsp;&nbsp;"
      name = " <span style='font-weight: normal'>Standard Inputs for CBA</span>"
      url = "/economics/cba/"
      identifier = "key-economics-cba"
      parent = "dashboard"
      weight = 39

  [[menu.main]]
    name = "Stakeholder views"
    pre = ""
    url = "/dashboard/stakeholder/"
    identifier = "stakeholder"   
    weight = 20
  [[menu.main]]
    pre = "<i class='fas fa-plane-arrival'></i>"
    name = "&nbsp;Airports"
    url = "/dashboard/stakeholder/airport/"
    identifier = "Airport"
    parent = "stakeholder"
    weight = 1  
    [[menu.main]]
    pre = "<i class='fas fa-compass'></i>"
    name = "&nbsp;Air navigation service provider"
    url = "/dashboard/stakeholder/ansp/"
    identifier = "Ansp"
    parent = "stakeholder"
    weight = 2
  [[menu.main]]
    pre = "<i class='fas fa-layer-group'></i>"
    name = "&nbsp;Functional airspace block"
    url = "/dashboard/stakeholder/fab/"
    identifier = "fab"
    parent = "stakeholder"
    weight = 3
  [[menu.main]]
    pre = "<i class='fas fa-globe'></i>"
    name = "&nbsp;States"
    url = "/dashboard/stakeholder/state/"
    identifier = "State"
    parent = "stakeholder"
    weight = 4

  [[menu.main]]
    name = "Data"
    pre = ""
    url = "/data/"
    identifier = "data" 
    weight = 30

  [[menu.main]]
    name = "Publications"
    pre = ""
    url = "/publications/"
    identifier = "publications" 
    weight = 40

  [[menu.main]]
    name = "Reference"
    url = "/reference/"
    identifier = "reference"
    weight = 50
  [[menu.main]]
    pre = "<i class='fas fa-marker'></i>"
    name = "&nbsp;Definitions"
    url = "/definition/"
    parent = "reference"
    weight = 2
  [[menu.main]]
    pre = "<i class='fas fa-wrench'></i>"
    name = "&nbsp;Methodology"
    url = "/methodology/"
    identifier = "methodology"
    parent = "reference"
    weight = 3
  [[menu.main]]
    pre = "<i class='fas fa-quote-left'></i>"
    name = "&nbsp;Acronyms"
    url = "/acronym/"
    parent = "reference"
    weight = 4
  [[menu.main]]
    pre = "<i class='fas fa-book'></i>"
    name = "&nbsp;Bibliography"
    url = "/bibliography/"
    parent = "reference"
    weight = 5

  [[menu.main]]
    name = "Links"
    identifier= "links"
    url = " "
    weight = 60
  [[menu.main]]
    name = "EUROCONTROL"
    post = " <i class='fas fa-xs fa-external-link-alt'></i>"
    url = "https://www.eurocontrol.int/"
    identifier = "ectl-link"
    parent = "links"
    weight = 1
  [[menu.main]]
    name = "Single European Sky (SES) portal"
    post = " <i class='fas fa-xs fa-external-link-alt'></i>"
    url = "https://www.eurocontrol.int/prudata/dashboard/"
    identifier = "ses-link"
    parent = "links"
    weight = 2
  [[menu.main]]
    name = "ICAO GANP"
    post = " <i class='fas fa-xs fa-external-link-alt'></i>"
    url = "https://www4.icao.int/ganpportal/"
    identifier = "icao-ganp-link"
    parent = "links"
    weight = 3
  [[menu.main]]
    name = "Connectivity dashboard"
    post = " <i class='fas fa-xs fa-external-link-alt'></i>"
    url = "https://ext.eurocontrol.int/connectivity_web/from"
    identifier = "connectivity-link"
    parent = "links"
    weight = 4
  [[menu.main]]
    name = "divider2"
    parent = "links"
    weight = 5
  [[menu.main]]
    name = "PRC Transformation Strategy"
    url = "/transformation/"
    parent = "links"
    weight = 6
  [[menu.main]]
    name = "PRC Open Performance Data Initiative"
    url = "https://opdi.aero"
    parent = "links"
    weight = 7
  
    
 [[menu.main]]
    name = "About"
    identifier= "about"
    url = "/about/us/"
    weight = 70
   [[menu.main]]
    name = "About the PRC"
    url = "/about/prc/"
    parent = "about"
    identifier = "prc"   
    weight = 1
  [[menu.main]]
    name = "About the AIU"
    url = "/about/aiu/"
    identifier = "aiu-page"
    parent = "about"
    weight = 2
  [[menu.main]]
    name = "About the PRU"
    url = "/about/us/"
    identifier = "pru"
    parent = "about"
    weight = 3
  [[menu.main]]
    name = "Release notes"
    url = "/post/"
    identifier = "release"
    parent = "about"
    weight = 4
  [[menu.main]]
    name = "Disclaimer"
    url = "/about/disclaimer/"
    identifier = "disclaimer"
    parent = "about"
    weight = 5
    


[[menu.traffic]]
    name = "Traffic"
    url = "/traffic"
    identifier= "overview"
    weight = 10
[[menu.traffic]]
    name = "Daily Traffic Dashboard"
    url = "https://www.eurocontrol.int/Economics/DailyTrafficVariation-States.html"
    post = " <i class='fas fa-xs fa-external-link-alt'></i>"
    identifier= "state"
    weight = 20
[[menu.traffic]]
    name = "Service Units"
    url = "https://www.eurocontrol.int/ServiceUnits/Dashboard/EnRouteMainDashboard.html"
    post = " <i class='fas fa-xs fa-external-link-alt'></i>"
    identifier= "su"
    weight = 30
[[menu.traffic]]
    name = "Traffic Forecasts"
    url = "/traffic/statfor"
    identifier= "statfor"
    weight = 40

[[menu.capacity]]
    name = "En-route & airport delay overview"
    url = "/capacity"
    identifier= "overview"
    weight = 10
 [[menu.capacity]]
    name = "En-route ATFM Delays"
    url = "/capacity/atfm_ert"
    identifier= "atfm_ert"
    weight = 20
[[menu.capacity]]
    name = "Airport ATFM Delays"
    url = "/capacity/atfm_apt"
    identifier= "atfm_apt"
    weight = 30
[[menu.capacity]]
    name = "All-causes Delay"
    url = "/capacity/tot_dly"
    identifier= "tot_dly"
    weight = 40
    
[[menu.efficiency]]
    name = "Efficiency Overview"
    url = "/efficiency"
    identifier= "overview"
    weight = 10
[[menu.efficiency]]
    name = "CO2 Emissions"
    url = "/efficiency/emissions"
    identifier= "emissions"
    weight = 15
[[menu.efficiency]]
    name = "Horizontal flight efficiency"
    url = "/efficiency/hfe"
    identifier= "hfe"
    weight = 20
[[menu.efficiency]]
    name = "Vertical flight efficiency"
    url = "/efficiency/vfe"
    identifier= "vfe"
    weight = 30
[[menu.efficiency]]
    name = "Terminal holdings"
    url = "/efficiency/asma"
    identifier= "asma"
    weight = 40
[[menu.efficiency]]
    name = "Taxi out"
    url = "/efficiency/taxiout"
    identifier= "taxiout"
    weight = 50
[[menu.efficiency]]
    name = "Taxi in"
    url = "/efficiency/taxiin"
    identifier= "taxiin"
    weight = 60

[[menu.economics]]
    name = "Economics Overview"
    url = "/economics"
    identifier= "overview"
    weight = 10
 [[menu.economics]]
    name = "ATM Cost Efficiency (ACE)"
    url = "/economics/ace-overview/"
    identifier= "ace"
    weight = 20
[[menu.economics]]
    name = "Unit rate and costs"
    url = "https://www.eurocontrol.int/ServiceUnits/Dashboard/EnRouteUnitRates.html"
    post = " <i class='fas fa-xs fa-external-link-alt'></i>"
    identifier= "unit"
    weight = 30
[[menu.economics]]
    name = "Service Units"
    url = "https://www.eurocontrol.int/ServiceUnits/Dashboard/EnRouteMainDashboard.html"
    post = " <i class='fas fa-xs fa-external-link-alt'></i>"
    identifier= "su"
    weight = 40
[[menu.economics]]
    name = "ANSP Financial dashboard"
    url = "/economics/finance/"
    identifier= "finance"
    weight = 50
[[menu.economics]]
    name = "Standard Inputs"
    url = "/economics/cba/"
    identifier= "cba"
    weight = 60


[[menu.publications]]
    name = "PRC News"
    url = "/publications/prc/news"
    identifier= "prc_news"
    weight = 10
[[menu.publications]]
    name = "PRR"
    url = "/publications/prc/prr"
    identifier= "prr"
    weight = 20
 [[menu.publications]]
    name = "ATM Cost Efficiency Benchmark (ACE)"
    url = "/publications/prc/ace"
    identifier= "ace"
    weight = 30
[[menu.publications]]
    name = "Other"
    url = "https://www.eurocontrol.int/ServiceUnits/Dashboard/EnRouteMainDashboard.html"
    post = " <i class='fas fa-xs fa-external-link-alt'></i>"
    identifier= "su"
    weight = 40





[params]
  includeBootstrapJs = false
  showActiveNav = true
  containerMaxWidth = "1200px"
  dateFormat = "Jan 2, 2006"
  hideFooter = false
  # HACK: DuckDuckGo multiple site search (i.e. separating sites with comma)
  #       does not work. So use 'OR site:' from the second on
  sitetosearch = "ansperformance.eu OR site:www.eurocontrol.int/prudata/dashboard/ OR site:www.eurocontrol.int/ACE/ OR site:www.eurocontrol.int/ServiceUnits/Dashboard/ OR site:www.eurocontrol.int/Economics/"
  privacyURL = "https://www.eurocontrol.int/info/privacy-and-website-terms-use"
  MathJaxCDN = "https://cdn.jsdelivr.net/npm/mathjax@2"

  [params.logo]
    url = "images/header/EUROCONTROL-logo-standard-rgb.svg"
    alt = "EUROCONTROL Supporting European Aviation logo"
    target = "https://eurocontrol.int"

  [params.owner]
    name = "European Organisation for the Safety of Air Navigation (EUROCONTROL)"
    shortname = "EUROCONTROL"
    location = "Brussels, Belgium"
    twitter = "eurocontrol"
    github =  "euctrl-pru"
    email = "PRU-Support@eurocontrol.int"


# see https://matjaz.it/hugo-power-user-make-it-web-friendly-1/
enableRobotsTXT = true

# see https://matjaz.it/hugo-power-user-make-it-web-friendly-1/
# TODO: set Google Webmaster tools
[sitemap]
  changefreq = "weekly"
  priority = 0.5