---
title: "PRC Data Challenges"
type: bibliography
date: "2025-09-01"
---

The [Performance Review Commission (PRC)](/about/prc) Data Challenge aims at engaging with
data scientists to create teams and compete to solve interesting data problem
for the Aviation community.
The focus is on **open data** and **open solutions** in order to achieve wide
distribution and reproducibility.


::: {class="container"}
:::: {class="row"}
::::: {class="card-deck"}

```{r echo=FALSE}
blogdown::shortcode(
  "bootstrap-card-alt",
  img="prc_dc25.jpeg",
  link="dc2025/",
  title="PRC Data Challenge 2025",
  text="predicting fuel burnt per segment of flight.", 
  alt="PRC Data Challenge 2025", 
  command="Resize", 
  options="300x", 
  class="mb-2"
  )
```



```{r echo=FALSE}
blogdown::shortcode(
  "bootstrap-card-alt",
  img="prc_dc24.jpeg",
  link="dc2024/",
  title="PRC Data Challenge 2024",
  text="Predicting take-off weight.", 
  alt="PRC Data Challenge 2024", 
  command="Resize", 
  options="300x", 
  class="mb-2"
  )
```



:::::
::::
:::
