---
layout: default
title: Michael STEINFURTH
permalink: /about/prc/prc_MS
---

<br>
**Michael STEINFURTH** joined the PRC in 2023 as the focal point for safety and civil-military cooperation.

Michael is a retired EUROCONTROL official, having had the privilege to serve from February 2012 to September 2021 as the Head of EUROCONTROL’s Civil-Military Cooperation Division.  

Before his assignment to EUROCONTROL in 2003 as Military Expert, Michael was an active serving Officer of the German Air Force with a background of military fighter pilot, flying RF-4s and F-4s, as well as T-38s as Instructor Pilot with in total more than 2800 flying hours. He commanded the GAF 511 Tactical Reconnaissance Squadron in Bremgarten, Germany and the 90th Flying Training Squadron of the EURO NATO Joint Jet Pilot Training in Sheppard AFB, Wichita Falls, Texas, USA.

Besides assignments to GAF Headquarters and NATO Air Command, he served in his last military assignment in the German Ministry of Defense, working on Safety, Flying Regulations and Flexible Use of Airspace, including matters of the back then just emerging Single European Sky.  
