---
layout: default
title: Ismail Hakki POLAT
permalink: /about/prc/prc_IP
---

<br>
**Ismail Polat** joined the PRC in 2021 as the focal point for airports.

Mr Polat; Senior Vice President of Development at Dubai Airports, the operator of Dubai International Airport (DXB) and Al Maktoum International Airport (DWC); has over 24 years of planning, design, construction, ORAT and operation experience in the aviation sector. 

Currently at Dubai Airports, he is managing the Research, Design, Programme and PMO teams, overseeing the development and enhancement of customer experience and operational efficiency at DXB while supporting the design and development of DWC from an airport operator point of view.

Previously he worked in the development of IGA Istanbul Airport, largest PPP green field airport project of the last decade, where his team provided full technical and engineering studies to entire airport organization with the aim of ensuring the operational integrity of the airport master plan and flexibility for future development in terms of airspace and airside infrastructure, CNS/ATM development and integration, aviation safety & security, operational effectiveness, level of service, constructability, infrastructure capacity, logistics and connectivity. Recently, several of the initiatives led by Mr. Polat, were awarded the very first SESAR JU-ACI Europe Digital Transformation Award received by IGA.


##### Qualifications

Airport planning, design, construction, operation, training and ORAT experience including airside, CNS/ATM, terminal, landside, cargo, MRO and airportopolis.

##### Education

Worcester Polytechnical Institute <br>
Worcester, MA / USA <br>
*M.Sc. studies in Construction Management, 2001*

Istanbul Technical University <br>
Istanbul / TURKEY <br>
*B.Sc. in Civil Engineering, 1998*