---
layout: default
title: Dr Peter WHYSALL
permalink: /about/prc/prc_PW
---

<br>

**Dr. Peter WHYSALL** joined the PRC in 2021 as the focal point for environment and now serves as chair having previously served as vice-chair.

Working within NATS for 23 years Pete rose most recently to the position of Director, Strategic Assurance and provided leadership for NATS strategy and investment planning for over 15 years.  

His input in a wide range of roles was always highly valued because of his ability to quickly synthesise complex information from multiple sources and to bring this together with clarity to build agreement and support decision making.  Similarly, his ability to speak with authority on a wide range of subjects has enabled him to provide thought leadership for numerous groups both inside and outside NATS.

During this time, he engaged widely with customers and within Europe including membership of the SESAR JU Admin Board and the Eurocontrol NDTECH and chairing the Agency Research Team (ART).  

At the same time, he led a range of different departments within NATS including Technical Strategy, System Architecture, Research and Development, Operational Analysis, Human Factors, Airspace Development, and Investment Management, helping to ensure that all of these became part of the bigger picture for NATS plans.

An engineer by background, Pete studied at the University of York for 7 years, obtaining a Master of Engineering in Computer Systems & Software Engineering and a Doctorate based on research into the use of Formal Methods in software development.  After leaving York he joined Roke Manor Research where he was involved primarily in the development of simulation software for surveillance, communications, and ATC concepts.  

Pete joined NATS in 1996 as Head of En Route Tools Research and was involved in a wide range of projects, including managing the Future Area Control Tools Support (FACTS) research project at its inception – an advanced set of controller tools which are now operational at the Swanwick Centre.  
Pete was keen to support the transition of research projects into implementation and joined the newly created Service Development & Investment Department in 2000 leading the integration of new concepts and tools into NATS’ investment programme and beginning his journey in strategy and investment.
