---
layout: default
title: Dr. Piotr IKANOWICZ
permalink: /about/prc/prc_PI
---

<br>

**Dr. Piotr IKANOWICZ** joined the PRC in 2023 as the focal point for airlines and serves as PRC chair.

Piotr has thirty plus years of executive track record in the aviation industry. While working as Chief Financial Officer of three carriers - LOT Polish, Malev Hungarian and Ukrainian Int’l (UIA), he has taken the lead on numerous major restructuring and turnaround projects. 

With a multicultural background, proficiency in four languages, and experience of working in different jurisdictions, he has cultivated his expertise in both favourable times (i.e. head of fleet selection committee) as well as challenging ones (i.e. dealing with an impact of shootdown of UIA Boeing 737). 

He started his career as Assistant professor in the Institute of International Economic Relations, Warsaw School of Economics (SGH), earning PhD in international economics (1990).

In parallel, he serves as a visiting lecturer at LAA (Warsaw), ALC (Luxembourg), and IIASL (Leiden).
