---
title: "Brazil"
---

Brazil and Europe represented by DECEA and EUROCONTROL engaged in 2016 in a cooperation agreement. Amongst other activities, this agreement entails the collaboration in developing in initial operational performance benchmarking exercise for Air Navigation Services (ANS).
Based on this agreement, DECEA started a Working Group, which has become the ATM Performance Indicators Management Committee, aiming at improving performance-based management. Through lessons learnt from the best practices observed at EUROCONTROL, and in particular PRU, DECEA established the Performance Section.

DECEA Performance Section and the PRU have established a joint project to foster the common understanding and harmonised interpretation of the proposed ICAO GANP indicators. The technical work has been conducted throughout the recent years comprising joint workshops and a series of web-based discussion sessions and face-to-face meetings. 
It also comprised the identification and validation of comparable data sources and joint data processing and analysis to produce this report.

<div class="col-sm-12">
<div class="container">
<div class="row">
<div class="card-deck">

```{r echo=FALSE}

blogdown::shortcode(
  "bootstrap-card-alt",
  img="x-cover-bra-eur-2024.png",
  link="bra-eur-2024/",
  title="16 June 2025",
  text="The fourth edition of the Brazil Europe Air Navigation Performance Comparison Report covers the period from 2019 to 2024. It introduces key updates, including an assessment of point merge implementation and a deeper ACC-level analysis, with a focus on Curitiba and Lisbon.", 
  alt="Comparison of Operational Air Navigation System Performance in Brazil and Europe 2019-2024", 
  command="Resize", 
  options="300x", 
  style="width: 18rem;", 
  class="mb-2"
  )

blogdown::shortcode(
  "bootstrap-card-alt",
  img="x-cover-bra-eur-2023.png",
  link="bra-eur-2023/",
  title="3 May 2024",
  text="This third edition of the bi-regional Brazil-Europe comparison report of Air Navigation System Performance continues to add transparent and robust data to support an informed discussion about operational performance in both regions.", 
  alt="Comparison of Operational Air Navigation System Performance in Brazil and Europe 2019-2023", 
  command="Resize", 
  options="300x", 
  style="width: 18rem;", 
  class="mb-2"
  )

blogdown::shortcode(
  "bootstrap-card-alt",
  img="x-cover-bra-eur-2022.png",
  link="bra-eur/",
  title="28 October 2022",
  text="The second edition of the Brazil-Europe Comparison of Operational ANS performance covers the years 2019-2021. For the first time, it includes an estimate of additional fuel burn in the taxi phase.   ", 
  alt="Comparison of Operational Air Navigation System Performance in Brazil and Europe 2019-2022", 
  command="Resize", 
  options="300x", 
  style="width: 18rem;", 
  class="mb-2"
  )

blogdown::shortcode(
  "bootstrap-card-alt",
  img="x-cover-bra-eur-2019.png",
  link="bra-eur-2019/",
  title="7 December 2021",
  text="This report comprises two parts: a description of the operational performance in Brazil and Europe for the years 2016-2019; and a description of the regional system characteristics in terms of traffic/demand evolution during the COVID-19 pandemic crisis.", 
  alt="Comparison of Operational Air Navigation System Performance in Brazil and Europe 2016-2019", 
  command="Resize", 
  options="300x", 
  style="width: 18rem;", 
  class="mb-2"
  )

```

</div>
</div>
</div>
</div>