---
title: CO₂ emissions by State
bibliography: ["../../../static/bib/aviation.bib"]
link-citations: true
slug: emissions
---
```{r echo = FALSE, message = FALSE, warning = FALSE}
# run setup script
source(here::here("_common.R"))
```
<br>

## Data source
The data is supplied by the [EUROCONTROL Aviation Sustainability Unit][env].


## Data description
The CO<sub>2</sub> emissions were calculated with the EUROCONTROL [Small Emitters Tool (SET)][set],
which enables to estimate the fuel burn and associated CO<sub>2</sub> emissions for an entire flight.
Hence, the results reflect total CO<sub>2</sub> emissions from controlled flights rather than ANSP/ATM performance. 

The **total CO<sub>2</sub> emissions for each State** were calculated based on **departing [IFR](/acronym/ifr/) flights**
billed by the [EUROCONTROL Route Charges Office][crco],
**aircraft type** and **actual flown distance** (full trajectory from origin to destination). 

For instance, the total CO<sub>2</sub> emissions for the full trajectory of a flight from Brussels to
New York would be included in the results for Belgium. 
A flight from New York to Brussels would however NOT be included in the results for Belgium.  


## Column naming and types

| Column name    | Description              | Example | Note |
|----------------|--------------------------|---------|------|
| YEAR           | Year                     | 2019    |      |
| MONTH          | Month                    | 1       |      |
| STATE_NAME     | State Name               | ALBANIA |For Excel, see META  sheet for presence of * |
| STATE_CODE     | State Code               | LA      |      |
| CO2_QTY_TONNES | CO2 Qty (for that state) | 8318.42 |      |
| TF             | traffic (for that state) | 821     |      |
| NOTE           | TRUE/FALSE for note      | TRUE    |Only in CSV |

Certain States' emissions have been aggregated specially:

* for the Excel file the STATE_NAME is marked with a '*' and the relevant info can be found in the META sheet.
* for CSV files an extra column NOTE has been added to note the special treatment (TRUE)
  - UNITED KINGDOM includes emissions for JERSEY, GUERNESEY, ISLE OF MAN
  - CYPRUS includes emissions for UK Sovereign Military bases on the island.
  - NORWAY includes emissions for Jan Mayen and Slavbarden.
  - DANEMARK includes emissions for FAROE ISLANDS.
  - PORTUGAL includes emissions for Azores and Madeira.
  - SPAIN does NOT included emissions for Canary Islands which are under 'CANARY ISLANDS'.
  - FRANCE emissions do NOT include those for French overseas territories.





[env]: https://www.eurocontrol.int/aviation-sustainability "EUROCONTROL Aviation Sustainability Unit"
[set]: https://www.eurocontrol.int/tool/small-emitters-tool "small emitters tool"
[crco]: https://www.eurocontrol.int/crco "EUROCONTROL Route Charges Office"