---
title: "Gate-to-Gate Emissions by State/Network"
bibliography: ../../../static/bib/aviation.bib
link-citations: true
slug: "g2g-emissions"
---
```{r echo = FALSE, message = FALSE, warning = FALSE}
# run setup script
source(here::here("_common.R"))
```
<br>
 
## Data source
The data is supplied by the [EUROCONTROL Performance Review Unit][pru] and the [EUROCONTROL Aviation Sustainability Unit][env].

## Data description
The CO<sub>2</sub>/NOX<sub>X</sub>/SO<sub>X</sub> emissions were calculated with the [EUROCONTROL Performance Review Unit][pru] and the [EUROCONTROL Aviation Sustainability Unit][env] Gate-to-Gate methodology which employs the [Advanced Emission Model (AEM)][aem] which is developed in the EUROCONTROL Innovation Hub by the [EUROCONTROL Aviation Sustainability Unit][aem]. The values provided in this data set are the historical emissions as displayed on the [EUROCONTROL FlyingGreen Platform][FG_NZ]. 
  
As explained on the [FlyingGreen Platform][FG_INFO], emission values are calculated with EUROCONTROL tool, Advance Emission Model, and based on the best available actual trajectory data available to EUROCONTROL. The FlyingGreen platform allows the user to select the methodology ('Area Focus' or 'Trajectory (UNFCCC) methodology'), the area of interest , and the traffic of interest (Flight type - DAIO) and returns the fuel burn and emission values based on the user's selection.

The past emissions are being presented using two different methodologies (these can be selected as filter options on the FlyingGreen platform):
 
 * <b>Trajectory (UNFCCC) methodology </b> with a State focus where the full trajectory of flight is considered; or
 * <b>Area focus</b> where the fuel burn and emissions are calculated only within the selected area and depending on the traffic selected (traffic type filer differentiating between departures, arrival and intra flights).

The data in these data sets provided here represent the <b>Area focus</b> methodology. In upcoming releases the available data will be expanded.  The gate-to-gate emissions provided here are calculated taking into account the individual trajectories (from gate-to-gate) of each flight and are modeled for all Flying Green flight phases:

  * taxi-out: The aircraft moves from the gate to the runway, preparing for take-off.
  * climb: The aircraft accelerates on the runway, lifts off and performs its ascent. 
  * cruise: The aircraft maintains a steady altitude and speed for the majority of the flight.
  * descent: The aircraft descends, aligns with the runway, touches down, and slows to taxi speed. 
  * taxi-in:  The aircraft moves from the runway to the gate or parking area after landing. 

In technical terms these Flying Green Flight Phases described above are subdivided in the following so called PRU Sub Phases which are used for the calculations of emissions within the trajectory.  

|Flying Green Flight Phase | PRU Sub Phase | Start                        | End                              |
|--------------------------|---------------|------------------------------|----------------------------------|
| Taxi-out                 | Taxi-out      | AOBT                         | ATOT - 42 sec (*)                |
| Climb                    | Take-off      | ATOT - 42 sec (*)            | ATOT                             |
| Climb                    | Climb-Out     | ATOT                         | First crossing of 3000 ft AGL    |
| Climb                    | Climb         | First crossing of 3000 ft AGL| Top of Climb                     |
| Cruise                   | Cruise        | Top of Climb                 | Top of Descent                   |
| Descent                  | Descent       | Top of Descent               | Last crossing of 3000 ft AGL     |
| Descent                  | Approach      | Last crossing of 3000 ft AGL | ALDT                             |
| Descent                  | Landing       | ALDT                         | ALDT + 40 sec (*)                |
| Taxi-in                  | Taxi-in       | ALDT + 40 sec (*)            | AIBT                             |

Note(s): 

(*): The take-off roll duration is defined to be standard 42 seconds and landing roll duration 40 seconds by the Reference Landing and Take-off (LTO) cycle. See [https://data.europa.eu/doi/10.2822/385503](https://data.europa.eu/doi/10.2822/385503).  


Abbreviation(s): 

  * AOBT: Actual Off-Block Time
  * ATOT: Actual Take-Off Time
  * AGL: Above Ground Level
  * ALDT: Actual Landing Time
  * AIBT: Actual In-Block Time

Subsequently these emissions are aggregated by the following variables: 
  
  * Area (Network or State)
  * Flight Type (DAIO)
  * Market Segment
  * Flight Phase

For more information on the methodologies see the description under ['READ MORE' for NetZero on FlyingGreen][FG_INFO].

## Column naming and types

| Column Name     | Description                                                                 | Example Values                                                                                 |
|-----------------|-----------------------------------------------------------------------------|------------------------------------------------------------------------------------------------|
| LEVEL           | Indicates the geographic aggregation level of the data.                    | `NETWORK`, `STATE`                                                                             |
| AREA            | Defines the area within the selected `LEVEL`.                              | If `LEVEL = NETWORK`: `ECAC`, `EEA`, `EU27`, `EU27 + EFTA`, `EUROCONTROL`, `RP3`<br>If `LEVEL = STATE`: ISO2 codes such as `BE`, `DE`, `PT - LISBON FIR`, `PT - SANTA MARIA FIR` |
| FOCUS_TYPE      | Indicates the methodology used to assign flights to areas.                 | `AREA FOCUS`                                                                                   |
| YEAR            | Year in which the emissions occurred.                                      | `2019`, `2020`, `2021`, `2022`, `2023`, `2024`                                                 |
| MONTH           | Month in which the emissions occurred.                                     | `1` = January through `12` = December                                                          |
| MARKET_SEGMENT  | Type of airline or operational market segment.                             | `business`, `cargo`, `lowcost`, `mainline`, `other`, `regional`                               |
| FLIGHT_TYPE     | Indicates the spatial flight type relative to the area.                    | `A` = Arrival<br>`D` = Departure<br>`I` = Internal<br>`O` = Overflight                         |
| FLIGHT_PHASE    | Segment of the flight in which emissions are calculated.                   | `cruise`, `descent`, `climb`, `taxi-in`, `taxi-out`                             |
| NB_FLIGHTS      | Number of flights matching all above criteria.                             | e.g., `3428`, `444`                                                                            |
| CO2_TONS        | Estimated CO₂ emissions (in metric tons) for these flights.                | e.g., `23112.0`, `2695.7`                                                                      |
| NOX_KG          | Estimated nitrogen oxides (NOₓ) emissions in kilograms.                    | e.g., `69539.62`, `8766.93`                                                                    |
| SOX_KG          | Estimated sulfur oxides (SOₓ) emissions in kilograms.                      | e.g., `6150.15`, `717.68`                                                                      |
## When to use this data

Use the **Gate-to-Gate Emissions** dataset when you need:

- **Detailed approach and granular estimates** of emissions based on actual flight trajectories and modeled with the **Advanced Emission Model (AEM)**.
- Emissions data that includes not only **CO₂**, but also **NOₓ** and **SOₓ**, distributed across **flight phases** (e.g., taxi-out, cruise, landing, etc.).
- Emissions **geographically attributed to the airspace or State where they occurred**, using the **Area Focus methodology**.
- Disaggregation by **flight type (DAIO)** and **market segment**, supporting detailed environmental performance analysis.
- Data coverage from **2019 onwards**, based on available historical emissions as published on the **FlyingGreen Platform**.

> *Note: This dataset is not yet updated monthly — the update process is being developed and will be available in the future.*

[pru]: http://127.0.0.1:4099/about/us/ "EUROCONTROL Performance Review Unit"
[aem]: https://www.eurocontrol.int/model/advanced-emission-model "Advanced Emission Model (AEM)"
[env]: https://www.eurocontrol.int/aviation-sustainability "EUROCONTROL Aviation Sustainability Unit"
[FG_NZ]: https://flying-green.eurocontrol.int/#/net-zero "FlyingGreen NetZero"
[FG_INFO]: https://www.eurocontrol.int/platform/flyinggreen "READ MORE for NetZero on FlyingGreen"
[AOBT]: https://ansperformance.eu/acronym/aobt/ "Actual Off-Block Time"