---
title: OBT - Off-Block Time
slug: obt
---


Airport Collaborative Decision-Making ([A-CDM][acdm])
describes different terms for OBT:

* [SOBT (Scheduled Off Block Time)][sobt]: The time that an aircraft is scheduled
  to depart from the parking position.
* [EOBT (Estimated Off Block Time)][eobt]: The estimated
  time that an aircraft will start movement associated with departure.
* [TOBT (Target Off Block Time)][tobt]: The time that an
  aircraft Operator or Ground handler estimates that an aircraft will be
  ready to startup/pushback immediately upon reception of clearance from the tower.
* TSAT (Target Start Up Approval Time): The time provided by ATC taking into
  account TOBT, CTOT and/or the traffic situation that an aircraft can expect start up/push back approval.
* [AOBT (Actual Off Block Time)][aobt]: The time the aircraft pushes back/vacates
  parking position.


## See Also

* [Airport Collaborative Decision-Making - A-CDM][acdm]
* [AOBT - Actual Off Block Time][aobt]
* [EOBT - Estimated Off Block Time][eobt]
* [SOBT - Scheduled Off Block Time][sobt]
* [TOBT - Target Off Block Time][tobt]

[acdm]: {{< relref "a-cdm.md" >}} "A-CDM - Airport Collaborative Decision-Making"
[aobt]: {{< relref "aobt.md" >}} "AOBT - Actual Off Block Time"
[eobt]: {{< relref "eobt.md" >}} "EOBT - Estimated Off Block Time"
[sobt]: {{< relref "sobt.md" >}} "SOBT - Scheduled Off Block Time"
[tobt]: {{< relref "tobt.md" >}} "TOBT - Target Off Block Time"
